### ISSUE TITLE
기기에 데이터 저장/불러오기

### ISSUE THREAD

**Issue by DiKaliZy** [ProjectInTheClass/Wish_List#11]
사용자 기기에 사용자가 등록한 정보를 저장하고 불러올 수 있도록 하기.

**Comment by DiKaliZy** [comment]
commit 번호 잘못 입력하였습니다. #11 --> #9

**Comment by drtsl** [comment]
class.swift 파일 마지막의 Items 부분을 변경하면 됩니다
