### ISSUE TITLE
이미지 파일(데이터) 기기와 연동

### ISSUE THREAD

**Issue by DiKaliZy** [ProjectInTheClass/Wish_List#6]
<주> iOS 기기 내부에 저장되어 있는 이미지(사진 등)를 불러와 항목등에 연동 및 저장시키기

<부> 카메라 기능과 연동시켜 즉시 촬영한 사진을 등록가능하게 하기

**Comment by Lahyllas** [comment]
#4 에서 완료했습니다.
카메라와 연동시키는 것은 당장은 불필요할 것 같습니다. 나중에 필요하다고 생각되면 추가하겠습니다.
