### ISSUE TITLE
항목 속성에 따른 분류 및 메인연동

### ISSUE THREAD

**Issue by DiKaliZy** [ProjectInTheClass/Wish_List#7]
<주> 즐겨찾기 / 마감임박 / 달성임박 등 항목들에게 부여할 속성 기준 정하고 적용시키기. + 메인 씬에 속성별 분류 출력

<부> 새로고침(각 속성을 가진 항목들 중 하나만 출력되므로 새로고침 버튼을 이용, 같은 속성 list에 들어있는 다른 항목들 번갈아가면서 표시) 기능

**Comment by Lahyllas** [comment]
#1 메인 구현과 동시에 진행하겠습니다.
